server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}  # Set this value in your environment or Docker config
            client-secret: ${GOOGLE_CLIENTSECRET}  # Set this value in your environment or Docker config
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8080}  # Ensure USER_SERVICE_BASEURL is set in your environment
          predicates:
            - Path=/users  # Match /users path in incoming requests
            - Method=POST  # Only for POST requests to /users
          filters:
            - SetPath=/api/user  # Rewrite the path for the backend service to /api/user

        - id: event-service
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8081}  # Ensure EVENT_SERVICE_BASEURL is set in your environment
          predicates:
            - Path=/events  # Match /events path in incoming requests
            - Method=GET  # Only for GET requests to /events
          filters:
            - SetPath=/api/event  # Rewrite the path for the backend service to /api/event

        - id: registration-service
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8082}  # Ensure REGISTRATION_SERVICE_BASEURL is set in your environment
          predicates:
            - Path=/register  # Match /register path in incoming requests
            - Method=POST  # Only for POST requests to /register
          filters:
            - SetPath=/api/registration  # Rewrite the path for the backend service to /api/registration

        - id: registration-service-all
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8082}  # Ensure REGISTRATION_SERVICE_BASEURL is set in your environment
          predicates:
            - Path=/registrations  # Match /registrations path in incoming requests
            - Method=GET  # Only for GET requests to /registrations
          filters:
            - SetPath=/api/registration/all  # Rewrite the path for the backend service to /api/registration/all
