server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: TRACE # Enable TRACE for debugging security

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${918676574540-4h053hi3jmt46cfks0h80qkstqmrtk7n.apps.googleusercontent.com}  # Set this value to the Google Client ID
            client-secret: ${918676574540-4h053hi3jmt46cfks0h80qkstqmrtk7n.apps.googleusercontent.com}  # Set this value to the Google Client Secret
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"  # The callback URL after login
            authorization-grant-type: authorization_code
            client-name: Google
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      routes:
        # User Service
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/users
          filters:
            - RemoveRequestHeader=Authorization # Remove header if service doesn't need authentication
            - SetPath=/api/user

        # Event Service
        - id: event-service
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/events
          filters:
            - RemoveRequestHeader=Authorization # Public endpoint
            - SetPath=/api/event

        # Registration Service (POST /register)
        - id: registration-service
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/register
            - Method=POST
          filters:
            - SetPath=/api/registration

        # Registration Service (GET /registrations)
        - id: registration-service-all
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/registrations
            - Method=GET
          filters:
            - PreserveHostHeader=true # Forward original host info
            - SetPath=/api/registration/all
