server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: TRACE # Enable TRACE for debugging security

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com # Ensure issuer matches your JWT
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs # Public key set for Google

  cloud:
    gateway:
      routes:
        # User Service
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/users
          filters:
            - RemoveRequestHeader=Authorization # Remove header if service doesn't need authentication
            - SetPath=/api/user

        # Event Service
        - id: event-service
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/events
          filters:
            - RemoveRequestHeader=Authorization # Public endpoint
            - SetPath=/api/event

        # Registration Service (POST /register)
        - id: registration-service
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/register
            - Method=POST
          filters:
            - SetPath=/api/registration

        # Registration Service (GET /registrations)
        - id: registration-service-all
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/registrations
            - Method=GET
          filters:
            - PreserveHostHeader=true # Forward original host info
            - SetPath=/api/registration/all
