server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: TRACE # Enable TRACE for debugging security

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${918676574540-4h053hi3jmt46cfks0h80qkstqmrtk7n.apps.googleusercontent.com}  # Set this value to the Google Client ID
            client-secret: ${918676574540-4h053hi3jmt46cfks0h80qkstqmrtk7n.apps.googleusercontent.com}  # Set this value to the Google Client Secret
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"  # The callback URL after login
            authorization-grant-type: authorization_code
            client-name: Google
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        # User Service
        - id: user-service-get-all
          uri: http://${USER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/users
          filters:
            - RemoveRequestHeader=Authorization
        - id: user-service-get-by-id
          uri: http://${USER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/users/{userId}
          filters:
            - RemoveRequestHeader=Authorization
        - id: user-service-register
          uri: http://${USER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/users/register
            - Method=POST
          filters:
            - RemoveRequestHeader=Authorization
        - id: user-service-update
          uri: http://${USER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/users/{userId}
            - Method=PUT
          filters:
            - RemoveRequestHeader=Authorization

        # Event Service
        - id: event-service-create
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/events
            - Method=POST
          filters:
            - RemoveRequestHeader=Authorization
        - id: event-service-get-by-names
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/events
            - Method=GET
          filters:
            - RemoveRequestHeader=Authorization
        - id: event-service-get-all
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/events/all
            - Method=GET
          filters:
            - RemoveRequestHeader=Authorization
        - id: event-service-get-by-id
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/events/{eventId}
            - Method=GET
          filters:
            - RemoveRequestHeader=Authorization

        # Registration Service
        - id: registration-service-register
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/registrations
            - Method=POST
          filters:
            - RemoveRequestHeader=Authorization
        - id: registration-service-get-by-user
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/registrations/user/{userId}
            - Method=GET
          filters:
            - RemoveRequestHeader=Authorization
        - id: registration-service-get-by-event
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/registrations/event/{eventId}
            - Method=GET
          filters:
            - RemoveRequestHeader=Authorization
        - id: registration-service-update-status
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/registrations/{registrationId}
            - Method=PATCH
          filters:
            - RemoveRequestHeader=Authorization
        - id: registration-service-cancel
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/registrations/{registrationId}
            - Method=DELETE
          filters:
            - RemoveRequestHeader=Authorization