name: Build, Test, and Deliver Services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  userservice:
    runs-on: ubuntu-latest
    name: Build, Test, and Deliver User Service
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt
      
      - name: Build, Test, and Package User Service
        working-directory: ./user-service
        run: mvn package -B

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/user-service:latest ./user-service

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USER }}/user-service:latest

  eventservice:
    runs-on: ubuntu-latest
    name: Build, Test, and Deliver Event Service
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt
      
      - name: Build, Test, and Package Event Service
        working-directory: ./event-service
        run: mvn package -B

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/event-service:latest ./event-service

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USER }}/event-service:latest

  registrationservice:
    runs-on: ubuntu-latest
    name: Build, Test, and Deliver Registration Service
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt
      
      - name: Build, Test, and Package Registration Service
        working-directory: ./registration-service
        run: mvn package -B

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/registration-service:latest ./registration-service

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USER }}/registration-service:latest

  apigateway:
    runs-on: ubuntu-latest
    name: Build, Test, and Deliver API Gateway
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt
      
      - name: Build, Test, and Package API Gateway
        working-directory: ./api-gateway
        run: mvn package -B

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/api-gateway:latest ./api-gateway

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USER }}/api-gateway:latest
